//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class batch
    {
        public batch()
        {
            this.registrations = new HashSet<registration>();
        }
    
        public int id { get; set; }
        [Display(Name = "Batch")]
        public string batch1 { get; set; }

        [Display(Name = "Year")] 
        public string year { get; set; }
    
        public virtual ICollection<registration> registrations { get; set; }
    }
}
