//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class course
    {
        public course()
        {
            this.registrations = new HashSet<registration>();
        }
    
        public int id { get; set; }

        [Display(Name = "Course")]
        public string course1 { get; set; }

        [Display(Name = "Duration (hours)")]
        public Nullable<int> duration { get; set; }
    
        public virtual ICollection<registration> registrations { get; set; }
    }
}
